# Generated by Django 5.0.1 on 2024-01-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='details',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
